# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_auto_20170121_1829'),
        ('customers', '0001_initial'),
        ('articles', '0004_auto_20170105_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7, unique=True, verbose_name='Invoice number')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoicedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Invoice text')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Unit price')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Amount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_articles', to='invoices.Invoice', verbose_name='Invoice')),
                ('original_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_article', to='articles.Article', verbose_name='Original article')),
            ],
            options={
                'verbose_name': 'Invoiced article',
                'verbose_name_plural': 'Invoiced articles',
            },
        ),
        migrations.CreateModel(
            name='InvoicedCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('salutation', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('FAMILY', 'Family')], max_length=20, verbose_name='Salutation')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Title')),
                ('company_name', models.CharField(blank=True, max_length=50, verbose_name='Company name')),
                ('street_address', models.CharField(blank=True, max_length=50, verbose_name='Street address')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Zip code')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_customer', to='invoices.Invoice', verbose_name='Invoice')),
                ('original_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_customer', to='customers.Customer', verbose_name='Original customer')),
            ],
            options={
                'verbose_name': 'Invoiced customer',
                'verbose_name_plural': 'Invoiced customers',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('name', models.CharField(choices=[('PENDING', 'Payment pending'), ('PAID', 'Paid'), ('TAXFILED', 'Taxes filed')], default='PENDING', max_length=20, verbose_name='State')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='invoices.Invoice', verbose_name='Invoice')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='invoices.State', verbose_name='Previous Transition')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='current_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='invoices.State', verbose_name='Current state'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Project'),
        ),
    ]
