# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='state',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_taxes_files',
            field=models.DateField(blank=True, null=True, verbose_name='Taxes filed'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
