# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20170125_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_taxes_files',
            new_name='date_taxes_filed',
        ),
    ]
