# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20170125_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedarticle',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Invoice text'),
        ),
    ]
