# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20170128_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='new_number',
            field=models.IntegerField(null=True),
        ),
    ]
