# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:35
from __future__ import unicode_literals

from django.db import migrations


def copy_invoice_numbers(app, schema_editor):
    Invoice = app.get_model('invoices', 'Invoice')
    for invoice in Invoice.objects.all():
        invoice.new_number = int(invoice.number)
        invoice.save()


class Migration(migrations.Migration):
    dependencies = [
        ('invoices', '0005_invoice_new_number'),
    ]

    operations = [
        migrations.RunPython(copy_invoice_numbers),
    ]
