# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoices', '0006_invoice_number_cast_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='new_number',
            new_name='number',
        )
    ]
