# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Invoice number'),
        ),
    ]
