# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20170221_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedarticle',
            name='kind',
            field=models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('REBATE', 'REBATE')], default='ARTICLE', max_length=10, verbose_name='Kind'),
        ),
    ]
