# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20170221_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedRebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ABS', 'Absolute'), ('PERC', 'Percentage'), ('ONEFREE', 'One free per')], max_length=10, verbose_name='Kind')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Invoice text')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Value')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_rebate', to='invoices.Invoice', verbose_name='Invoice')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Rebate',
                'verbose_name_plural': 'Rebates',
            },
        ),
        migrations.CreateModel(
            name='Rebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ABS', 'Absolute'), ('PERC', 'Percentage'), ('ONEFREE', 'One free per')], max_length=10, verbose_name='Kind')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Invoice text')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Value')),
                ('auto_apply', models.BooleanField(verbose_name='Apply automatically')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Rebate',
                'verbose_name_plural': 'Rebates',
            },
        ),
    ]
