# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0003_auto_20170319_1132'),
        ('invoices', '0010_appliedrebate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedrebate',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='rebates',
            field=models.ManyToManyField(blank=True, to='rebates.Rebate', verbose_name='Rebates'),
        ),
        migrations.DeleteModel(
            name='AppliedRebate',
        ),
    ]
