# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20170327_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedarticle',
            name='original_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_articles', to='articles.Article', verbose_name='Original article'),
        ),
    ]
