# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20170903_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedarticle',
            name='original_article',
        ),
        migrations.RemoveField(
            model_name='invoicedcustomer',
            name='original_customer',
        ),
    ]
