language: python
python:
  - "3.5"
#install:
#  - virtualenv ~/jepvenv
#  - source ~/jepvenv/bin/activate
#  - pip install pytest-cov coveralls
#  - pip install .
#  - pip list
script:
  - py.test test #--cov=jep_py
#after_success:
#  - coveralls