language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls
  - npm install -g bower
  - bower install
  - rm bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker-standalone.css
before_script:
  - export version=`python -m bizwiz.version`
  - export image=mpagel/bizwiz:$version
script:
  - py.test test -v --cov=bizwiz
after_success:
  - coveralls
  - echo $image
