language: python
sudo: required
services:
  - docker
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls
  - npm install -g bower
  - bower install
  - rm bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker-standalone.css
before_script:
  - if [ -n "$TRAVIS_TAG" ]; then
      export image=mpagel/bizwiz:${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER};
    else
      export image=mpagel/bizwiz:dev-${TRAVIS_BUILD_NUMBER};
    fi
script:
  - py.test test -v --cov=bizwiz
  - docker build -t $image .
after_success:
  - coveralls
  - if [ -n "$TRAVIS_TAG" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $image;
    fi
