dist: xenial
language: python
sudo: required
services:
  - docker
python:
  - 3.7
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls codecov
  - npm install -g bower
  - bower install
  - rm bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker-standalone.css
before_script:
  - export repo=mpagel/bizwiz
  - rm -f build-info
  - if [ -n "$TRAVIS_TAG" ]; then
      export image=${repo}:${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER};
      echo $image > build-info;
    else
      export image=${repo}:dev-${TRAVIS_BUILD_NUMBER};
    fi
script:
  - py.test test -v --cov=bizwiz
  - docker build -t ${repo}:latest -t $image .
after_success:
  - coveralls
  - codecov
  - if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $image;
      docker push ${repo}:latest;
    fi
