language: python
sudo: required
services:
  - docker
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls
  - npm install -g bower
  - bower install
  - rm bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker-standalone.css
script:
  - py.test test -v --cov=bizwiz
after_success:
  - coveralls
  - export image=mpagel/bizwiz:$TRAVIS_TAG-$TRAVIS_COMMIT
  - docker build -t $image .
  - if [ -n "$TRAVIS_TAG" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $image;
    fi
