# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20161222_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='inactive',
            field=models.BooleanField(default=False, help_text='Inactive articles can no longer be used in projects and invoices.', verbose_name='Inactive'),
        ),
    ]
