# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedrebate',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='AppliedRebate',
        ),
    ]
