# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0002_auto_20170319_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebate',
            name='auto_apply',
            field=models.BooleanField(verbose_name='Automatic'),
        ),
    ]
