# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('salutation', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('FAMILY', 'Family')], max_length=20, verbose_name='Salutation')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Title')),
                ('company_name', models.CharField(blank=True, max_length=50, verbose_name='Company name')),
                ('street_address', models.CharField(blank=True, max_length=50, verbose_name='Street address')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Zip code')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone number')),
                ('mobile_number', models.CharField(blank=True, max_length=50, verbose_name='Mobile number')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
