# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170105_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
