# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='customers',
            field=models.ManyToManyField(to='customers.Customer', verbose_name='Customers in group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='articles',
            field=models.ManyToManyField(to='articles.Article', verbose_name='Articles in project'),
        ),
    ]
